name: CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: "1.2.0"
      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Change directories
        run: |
          ls
          cd librtd
          ls
      - name: Install dependencies
        run: nimble install -Y
      - name: Run tests
        run: nimble test
