name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: "1.0.2"
      - name: Nim version check
        run: |
          nim -v
          nimble -v
      - name: Install dependencies
        run: nimble install -Y
      - name: Run tests
        run: nimble test
