name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nim
        uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: "1.0.4"
      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Install dependencies
        run: nimble install -Y
      - name: Run tests
        run: nimble test
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@master
      with:
        nim-version: "1.0.4"
    - name: Install dependencies
      run: nimble install -Y
    - name: Verify project compiles
      run: nimble build
    - name: Print librtd version from compiled CLI
      run: ./librtd -v
    
    

