name: CI

on: [push]

jobs:
  test-api:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: "1.2.0"
      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Install dependencies
        run: nimble install -Y
      - name: Run tests
        run: nimble test
  test-cli:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1.0.2
        with:
          nim-version: "1.2.0"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools nimporter
          nimble install -Y
      - name: Install librtd
        run: pip install -e .
      - name: Check CLI worked
        run: librtd --version
